# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Justin 111 Smith
email: justin111smith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Justin here.  This is my first GitHub site and will document as I learn more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://justin111smith.com" # the base hostname & protocol for your site
twitter_username: justinfinity
github_username:  jekyll

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine
